networks:
    alfred-dev:
        external: true
services:
    mongo:
        container_name: my_mongo
        environment:
            MONGO_INITDB_ROOT_PASSWORD: root
            MONGO_INITDB_ROOT_USERNAME: root
        image: mongo:7.0
        networks:
            alfred-dev: {}
        ports:
            - 27017:27017
        restart: unless-stopped
        volumes:
            - mongo-data:/data/db
version: "3.9"
volumes:
    mongo-data: null
